### PR TITLE
 feat: add typescript types + type tests

### PR DESCRIPTION
**Pull request by wemeetagain**
Dependent on  multiformats/js-multiaddr#105 and multiformats/js-mafmt#48

### CODE REVIEW

**Comment by vasco-santos** [comment]
Thanks for the PR @wemeetagain 

Now that both dependent PRs got merged, is this ready for review?

**Comment by wemeetagain** [comment]
@vasco-santos 
I just bumped the versions of the dependencies, its ready for review :+1:

**Comment by wemeetagain** [comment]
I think travis just needs to be restarted

**Comment by vasco-santos** [comment]
Restarting it

**Pull request merged**
