### PR TITLE
fix(package): add missing lodash.uniqby dependency.

### PR DESCRIPTION
**Pull request by haadcode**
Add lodash.uniqby to package.json as it's required by index.js

### CODE REVIEW

**Comment by dignifiedquire** [comment]
thanks lgtm

**Comment by dignifiedquire** [comment]
actually `master` uses `lodash` directly Oo can you please change that so it actually uses just this package?

**Comment by haadcode** [comment]
As far as I can tell it's only used in that one place: https://github.com/libp2p/js-peer-info/search?utf8=%E2%9C%93&q=lodash. Let me know if I'm missing something. If not, we're better off using the individual dep instead of pulling in whole of lodash as it gives us a smaller footprint (I know you know this :)).

**Comment by dignifiedquire** [comment]
yeah I meant if you can change the require to 'lodash.uniqby' instead of lodash

**Comment by haadcode** [comment]
Ah! :) Now I understand what you meant. Fixed, pushed and squashed.

**Comment by diasdavid** [comment]
Nice, thank you for adopting our commit guidelines, @haadcode :)

**Pull request merged**
